#!/usr/bin/python
import socket


def create_connection(hostname, file_name_to_send):
    server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    host = hostname
    port = 4444
    server_socket.bind((host, port))
    server_socket.listen(5)
    while True:
        connection_socket, address = server_socket.accept()
        print("Connection established from".format(str(address)))
        send_file(connection_socket, file_name_to_send)


def send_file(connection_socket, file_name):
    file_content = open(file_name, 'rb')
    load = file_content.read(1024)
    while load:
        connection_socket.send(load)
        print('Sent ', repr(load))
        load = file_content.read(1024)
    connection_socket.close()


def main():
    create_connection('127.0.0.1', "test")


if __name__ == "__main__":
    main()

