#!/usr/bin/python
import subprocess


def run_file(filename_to_run, filename_to_store_output):
	subprocess.call(["chmod", "+x", filename_to_run])
	result = subprocess.Popen(['bash', filename_to_run])
	print(result, open(filename_to_store_output, "w"))


def main():
    run_file("abc", "jobs_results/")


if __name__ == '__main__':
    main()
